// ======================== 1) Application Configuration and State Management ========================
const API_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/models';
const MODEL_FALLBACKS = ['gemini-2.5-flash', 'gemini-1.5-flash'];
let API_KEY = window.GEMINI_API_KEY || localStorage.getItem('GEMINI_API_KEY') || '';
let dom = {};

// ======================== 2) DOM Helpers ========================
// Fast shortcuts for selecting elements
const getElement = (id) => document.getElementById(id);
const getElements = (selector) => document.querySelectorAll(selector);

// Show and hide inline error message block
const showError = (message) => {
    if (!dom.errorMessage) return;
    dom.errorMessage.textContent = message;
    dom.errorMessage.classList.remove('hidden');
};

const hideError = () => {
    if (!dom.errorMessage) return;
    dom.errorMessage.textContent = '';
    dom.errorMessage.classList.add('hidden');
};

// ======================== 3) API Key Handling ========================
// Validate key from memory/config; ask user only if missing
const validateAPIKey = () => {
    if (API_KEY) return true;
    
    const userKey = prompt('⚠️ API Key Required\n\nGet FREE key at: https://aistudio.google.com/app/apikey');
    if (userKey?.trim()) {
        API_KEY = userKey.trim();
        localStorage.setItem('GEMINI_API_KEY', API_KEY);
        alert('✅ API key saved!');
        return true;
    } else {
        alert('❌ API key required');
        return false;
    }
};

const resetAPIKey = () => {
    API_KEY = '';
    localStorage.removeItem('GEMINI_API_KEY');
};

// ======================== 4) Input Utilities ========================
// Run a callback when Enter is pressed in an input
const onEnterPress = (inputElement, callback) => {
    inputElement?.addEventListener('keypress', (event) => {
        if (event.key === 'Enter') callback();
    });
};

// Convert plain lines into a numbered list for Idea output
const formatNumberedList = (responseText) => {
    return responseText
        .split('\n')
        .filter(line => line.trim())
        .map((line, index) => /^\d+\./.test(line) ? line : `${index + 1}. ${line}`)
        .join('\n');
};

// ======================== 5) Gemini API Client ========================
// Send prompt to Gemini and return plain text result
const callGeminiAPI = async (prompt) => {
    let lastError = 'API Error';

    for (const model of MODEL_FALLBACKS) {
        try {
            const apiUrl = `${API_BASE_URL}/${model}:generateContent?key=${API_KEY}`;
            const response = await fetch(apiUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }]
                })
            });

            const data = await response.json().catch(() => ({}));

            if (response.ok) {
                const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
                if (text?.trim()) return text;
                return 'No response generated by model.';
            }

            const errorMessage = data?.error?.message || `Request failed with status ${response.status}`;
            lastError = errorMessage;

            // Retry with fallback model only when model is unavailable.
            const isModelIssue = response.status === 404 || /not found|unsupported|model/i.test(errorMessage);
            if (isModelIssue) continue;

            // For key/auth errors, stop retrying and return clear guidance.
            const isAuthIssue = response.status === 401 || response.status === 403 || /api key|permission|unauthorized|forbidden/i.test(errorMessage);
            if (isAuthIssue) {
                resetAPIKey();
                return 'API key invalid or expired. Please enter a valid Gemini API key and try again.';
            }

            return errorMessage;
        } catch (error) {
            lastError = 'Network error. Check internet connection and try again.';
        }
    }

    return lastError;
};

// ======================== 6) UI State Helpers ========================
// Show selected feature tab and hide others
const switchFeatureTab = (featureName) => {
    dom.tabButtons?.forEach(btn => 
        btn.classList.toggle('active', btn.dataset.feature === featureName)
    );
    dom.contentSections?.forEach(section => 
        section.classList.toggle('active', section.id === featureName)
    );
};

// Generic runner for all features: validate -> request -> render
const handleFeature = async (inputElement, promptFunction, outputElement, formatterFunction = (x) => x) => {
    if (!validateAPIKey()) return;
    hideError();
    
    const userInput = inputElement.value.trim();
    if (!userInput) return;
    
    dom.loadingSpinner?.classList.remove('hidden');
    
    try {
        // Generate prompt dynamically if function provided
        const fullPrompt = typeof promptFunction === 'function' ? 
            promptFunction(userInput) : 
            promptFunction;
        
        const response = await callGeminiAPI(fullPrompt);

        if (/api key invalid or expired/i.test(response)) {
            showError(response);
            alert(response);
            return;
        }

        if (/request failed|network error|api error|quota|permission|forbidden|unauthorized|rate limit|resource exhausted/i.test(response)) {
            showError(response);
            return;
        }

        const formattedResponse = formatterFunction(response);
        
        outputElement.textContent = formattedResponse;
        outputElement.parentElement.classList.remove('hidden');
        inputElement.value = '';
    } catch (error) {
        showError('Something went wrong. Please try again.');
    } finally {
        dom.loadingSpinner?.classList.add('hidden');
    }
};

// ======================== 7) App Bootstrap ========================
document.addEventListener('DOMContentLoaded', () => {
    // 7.1) Cache frequently used DOM nodes
    dom = {
        tabButtons: getElements('.tab-btn'),
        contentSections: getElements('.feature-content'),
        // Ask Anything
        questionInput: getElement('questionInput'),
        answerContent: getElement('answerContent'),
        // Summarize
        textInput: getElement('textToSummarize'),
        summaryContent: getElement('summaryContent'),
        // Generate Ideas
        ideaPrompt: getElement('ideaPrompt'),
        ideaCount: getElement('ideaCount'),
        ideasContent: getElement('ideasContent'),
        // Define Term
        termInput: getElement('termInput'),
        definitionContent: getElement('definitionContent'),
        // UI Elements
        loadingSpinner: getElement('loadingSpinner'),
        errorMessage: getElement('errorMessage')
    };

    // 7.2) Tab navigation binding
    dom.tabButtons.forEach(button => {
        button.onclick = (event) => switchFeatureTab(event.target.dataset.feature);
    });

    // 7.3) Ask Anything bindings
    getElement('askBtn').onclick = () => 
        handleFeature(dom.questionInput, (q) => `Answer: ${q}`, dom.answerContent);
    onEnterPress(dom.questionInput, () => 
        handleFeature(dom.questionInput, (q) => `Answer: ${q}`, dom.answerContent));

    // 7.4) Summarizer bindings
    getElement('summarizeBtn').onclick = () => 
        handleFeature(dom.textInput, (t) => `Summarize in 2-3 sentences:\n\n${t}`, dom.summaryContent);

    // 7.5) Idea Spark bindings
    getElement('generateIdeasBtn').onclick = () => 
        handleFeature(
            dom.ideaPrompt,
            (idea) => `Generate ${dom.ideaCount.value} ideas about: "${idea}"`,
            dom.ideasContent,
            formatNumberedList
        );
    onEnterPress(dom.ideaPrompt, () => 
        handleFeature(
            dom.ideaPrompt,
            (idea) => `Generate ${dom.ideaCount.value} ideas about: "${idea}"`,
            dom.ideasContent,
            formatNumberedList
        ));

    // 7.6) Definition Finder bindings
    getElement('defineBtn').onclick = () => 
        handleFeature(
            dom.termInput,
            (term) => `Define "${term}" with etymology, examples, and related concepts`,
            dom.definitionContent
        );
    onEnterPress(dom.termInput, () =>
        handleFeature(
            dom.termInput,
            (term) => `Define "${term}" with etymology, examples, and related concepts`,
            dom.definitionContent
        ));

    // 7.7) Initial screen
    switchFeatureTab('ask-anything');
});
